name: Docker Image CI

on:
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: npm ci
      working-directory: ./backend

    - name: Type check
      run: npm run typecheck
      working-directory: ./backend
      
    - name: Build the Docker image
      run: docker build -t express-app-test ./backend
    
